export const GET_BUSINESS_NEWS_REQUEST = 'GET_BUSINESS_NEWS_REQUEST';
export const GET_BUSINESS_NEWS_SUCCESS = 'GET_BUSINESS_NEWS_SUCCESS'; // Fixed this line
export const GET_BUSINESS_NEWS_FAILURE = 'GET_BUSINESS_NEWS_FAILURE'; // Fixed this line

export const GET_CRYPTO_NEWS_REQUEST = 'GET_CRYPTO_NEWS_REQUEST';
export const GET_CRYPTO_NEWS_SUCCESS = 'GET_CRYPTO_NEWS_SUCCESS'; // Fixed this line
export const GET_CRYPTO_NEWS_FAILURE = 'GET_CRYPTO_NEWS_FAILURE'; // Fixed this line

export const GET_SPORTS_NEWS_SUCCESS = 'GET_SPORTS_NEWS_SUCCESS'; // Fixed this line
export const GET_SPORTS_NEWS_FAILURE = 'GET_SPORTS_NEWS_FAILURE';
export const GET_SPORTS_NEWS_REQUEST = 'GET_SPORTS_NEWS_REQUEST';

export const GET_POLITICAL_NEWS_REQUEST = 'GET_POLITICAL_NEWS_REQUEST';
export const GET_POLITICAL_NEWS_SUCCESS = 'GET_POLITICAL_NEWS_SUCCESS'; // Fixed this line
export const GET_POLITICAL_NEWS_FAILURE = 'GET_POLITICAL_NEWS_FAILURE';