export const GET_BUSINESS_NEWS_REQUEST = 'GET_BUSINESS_NEWS_REQUEST';
export const GET_BUSINESS_NEWS_SUCCESS = 'GET_BUSINESS_NEWS_SUCCESS'; // Fixed this line
export const GET_BUSINESS_NEWS_FAILURE = 'GET_BUSINESS_NEWS_FAILURE'; // Fixed this line

export const GET_CRYPTO_NEWS_REQUEST = 'GET_CRYPTO_NEWS_REQUEST';
export const GET_CRYPTO_NEWS_SUCCESS = 'GET_CRYPTO_NEWS_SUCCESS'; // Fixed this line
export const GET_CRYPTO_NEWS_FAILURE = 'GET_CRYPTO_NEWS_FAILURE'; // Fixed this line
